### ISSUE TITLE
Unity 2019.x - custom manifest

### ISSUE THREAD

**Issue by nektoid** [EnoxSoftware/MagicLeapWithOpenCVForUnityExample#3]
Hi, I have a conflict when building in Unity 2019.1.6f.1. On their website ML say: 

> The custom manifest replaces the Privilege checkboxes found in Player Settings - Publishing Settings in MLTP versions of the editor.

Could you update the example so it requests the CameraCapture permission via custom manifest as described on [ML Creator's portal](https://creator.magicleap.com/learn/guides/declare-your-manifest#manifest-files-with-the-unity-editor)? I currently get build error saying that the package

> already has a USES declaration! You may not have your own "USES=" statement in the .package file.

Thanks!

**Comment by EnoxSoftware** [comment]
Please copy manifest.xml to add camera capture privileges.
https://creator.magicleap.com/learn/guides/migrate-unity-editors
NEW with 2019.x - Use a custom manifest to add privileges and modify your API level. A template manifest is located in Assets/MagicLeap/Examples/Plugins/Lumin/manifest.xml. Copy it to Assets/Plugins/Lumin/manifest.xml and modify it.

> already has a USES declaration! You may not have your own "USES=" statement in the .package file.
https://forum.unity.com/threads/2019-1-3-exception-package-file-already-has-a-uses-declaration.680809/
In my environment, this error was resolved once I deleted the com.company.productname.package file.

**Comment by nektoid** [comment]
Thank you!
