### ISSUE TITLE
MagicLeapArUcoExample is just a blank screen 

### ISSUE THREAD

**Issue by ceinem** [EnoxSoftware/MagicLeapWithOpenCVForUnityExample#8]
The Image Capture examples works find, but in the Aruco Tracker Example I just get a blank screen. 
This might be a similar issue as #6 

Looking at the Debug Console is raises issues with the Canvas. That in VR mode the Canvas might not be visible. My attempts at changing the Canvas settings to fix it failed so far though

**Comment by EnoxSoftware** [comment]
Thank you very much for reporting.

Could you tell me the environment you tried?
LuminOS version : 
OpenCV for Unity version : 
Unity version :

**Comment by ceinem** [comment]
Yes, sure. 
LuminOS version: 0.98.01
OpenCV for Unity: 2.3.8
Unity: 2019.2.20f1

**Comment by EnoxSoftware** [comment]
Are you using MLSDK 0.23.0?

**Comment by ceinem** [comment]
yes

**Comment by EnoxSoftware** [comment]
Could you try the steps below?

1. Setup New Unity Project . https://developer.magicleap.com/learn/guides/unity-setup ( Import the Magic Leap Unity Package 0.23.0 )<img width="708" alt="magicleap_xr_management" src="https://user-images.githubusercontent.com/7920392/76441328-932af680-6402-11ea-8a25-da6e55e522c3.PNG">

1. Import the OpenCVForUnity2.3.8.
1. Import the MagicLeapWithOpenCVForUnityExample.unitypackage 1.0.5.
1. Check CameraCapture and ComputerVision checkbox in Publishing Settings. ( Minimum API Level 7 )<img width="705" alt="magicleap_manifest" src="https://user-images.githubusercontent.com/7920392/76441386-aa69e400-6402-11ea-852a-200758b0bafe.PNG">
1. Check CameraCapture and ComputerVision checkbox in Privilege Requester.<img width="583" alt="magicleap_privilege" src="https://user-images.githubusercontent.com/7920392/76441589-02084f80-6403-11ea-925a-1d84bd93a468.PNG">

If you get an error with Canvas, try disabling Canvas.
<img width="1182" alt="magicleap_canvas" src="https://user-images.githubusercontent.com/7920392/76442679-a212a880-6404-11ea-8347-fa307669e7e5.PNG">

**Comment by artiransaygin** [comment]
@ceinem were you able to find a solution for this blank screen issue?

**Comment by EnoxSoftware** [comment]
It seems that the API has changed significantly in Lumin SDK 0.24.
I'm in the process of fixing MagicLeapWithOpenCVForUnityExample. I am terribly sorry, but please wait for a while.

**Comment by ceinem** [comment]
Sorry, I never got it running, but I took the code apart and repurposed what I needed for my project. So I don't need the example anymore. 

Also I've been told, that there is now a native Aruco tracker in the Lumin SDK. MLArucoTrackerCreate() or something like that is the API apparently. 
But I haven't tested it yet.
